LoyaltyCardsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: LoyaltyCards-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: CardNumber
        AttributeType: S
    KeySchema:
      - AttributeName: CardNumber
        KeyType: HASH
